### PR TITLE
healthcheck

### PR DESCRIPTION
**Pull request by drewkit**

### CODE REVIEW

**Comment by drewkitch** [comment]
need to update `docker-compose.yml`

**Comment by drewkit** [comment]
cc @kellyjandrews

**Comment by mlocher** [comment]
Why are we removing the tag from the `postgres` image? This could cause the builds to break if Postgres updates their `latest` tag, and we don't support that version yet.

This applies to all other PRs as well, e.g. https://github.com/codeship-library/ruby-rails-todoapp/pull/8, https://github.com/codeship-library/php-laravel-todoapp/pull/5, https://github.com/codeship-library/python-django-todoapp/pull/1, https://github.com/codeship-library/nodejs-express-todoapp/pull/3 

On a separate note, why is this the only example that's not using the `alpine` based version?

**Review by ethangj — APPROVED** [review]

**Review by ethangj — CHANGES_REQUESTED** [review]
Would explicitly switch to latest or alpine tag

**Comment by drewkit** [comment]
@mlocher the Docker Hub healthcheck images only offer `latest` or `alpine` as tag options for the `postgres` image.

If we think its going to be a problem, we could certainly replace the `healthcheck/postgres` image with a Dockerfile specifying a version of PostgreSQL as its base image and includes a healthcheck instruction.

**Comment by mlocher** [comment]
@drewkitch yeah, I just had the same conversation with @ethangj. Sorry I missed this.

In that case I'd prefer using the `alpine` versions (since it's simply smaller), but that's not a blocking requirement.

**Review by ethangj — APPROVED** [review]

**Pull request merged**
